backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
    - name: "artist"
      label: "Artists"
      folder: "artists"
      create: true
      slug: "{{name}}"
      fields:
        - {label: "ID", name: "id", widget: "string"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Name", name: "name", widget: "string"}
        - {label: "Bio", name: "bio", widget: "markdown"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Link", name: "link", widget: "string"}
        - {label: "Time", name: "time", widget: "datetime"}
        - {label: "Contact Email", name: "email", widget: "string"}

    - name: "porches"
      label: "Porches"
      folder: "porches"
      create: true
      slug: "{{house_number}}-{{street_name}}"
      fields:
        - {label: "ID", name: "id", widget: "string"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Message", name: "message", widget: "text"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Host", name: "host", widget: "string"}
        - {label: "House Number", name: "house_number", widget: "string"}
        - {label: "Street Name", name: "street_name", widget: "string"}
        - {label: "Latitude", name: "lat", widget: "string", comment: "Leaving latitude/longitude fields blank will remove the porch from the Porchfest map.", required: false}
        - {label: "Longitude", name: "long", widget: "string", comment: "Leaving latitude/longitude fields blank will remove the porch from the Porchfest map.", required: false}
        - {label: "Contact Email", name: "email", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "Artist - Noon"
          name: "artist12"
          widget: "relation"
          collection: "artist"
          searchFields: ["name"]
          display_fields: ["{{name}}"]
          valueField: "id"
          required: false
        - label: "Artist - 1pm"
          name: "artist1"
          widget: "relation"
          collection: "artist"
          searchFields: ["name"]
          display_fields: ["{{name}}"]
          valueField: "id"
          required: false
        - label: "Artist - 2pm"
          name: "artist2"
          widget: "relation"
          collection: "artist"
          searchFields: ["name"]
          display_fields: ["{{name}}"]
          valueField: "id"
          required: false
        - label: "Artist - 3pm"
          name: "artist3"
          widget: "relation"
          collection: "artist"
          searchFields: ["name"]
          display_fields: ["{{name}}"]
          valueField: "id"
          required: false
        - label: "Artist - 4pm"
          name: "artist4"
          widget: "relation"
          collection: "artist"
          searchFields: ["name"]
          display_fields: ["{{name}}"]
          valueField: "id"
          required: false
        - label: "Artist - 5pm"
          name: "artist5"
          widget: "relation"
          collection: "artist"
          searchFields: ["name"]
          display_fields: ["{{name}}"]
          valueField: "id"
          required: false
